#calculate the  total revenue generated by two product categories in a store
import numpy as np

# Define two arrays
a = np.array([500, 600, 700,550])  # Example revenue for products in Category A
b = np.array([450, 700, 800,600])   # Example revenue for products in Category B

# Add the arrays element-wise
c = np.add(a, b)

# Print the result
print("total revenue is:",c)
